Test2/Demo/mdapipkg/unpackaged/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JoinDate__c</fullName>
        <label>JoinDate</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mail__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Mail</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member_of_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member of Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Member of Project</relationshipLabel>
        <relationshipName>Member_of_Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch Manager</fullName>
                </value>
                <value>
                    <fullName>Project manager</fullName>
                </value>
                <value>
                    <fullName>Programmer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP{00000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test2/Demo/mdapipkg/unpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects Members</relationshipLabel>
        <relationshipName>ProjectsMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PM_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PM Name</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>PM of Project(s)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ{00000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test2/Demo/mdapipkg/unpackaged/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Task_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Create Design</fullName>
                </value>
                <value>
                    <fullName>Self-Review Design</fullName>
                </value>
                <value>
                    <fullName>Correct Design</fullName>
                </value>
                <value>
                    <fullName>Review Design</fullName>
                </value>
                <value>
                    <fullName>Fixbug</fullName>
                </value>
                <value>
                    <fullName>Read Design</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Self-Review Code</fullName>
                </value>
                <value>
                    <fullName>Correct Code</fullName>
                </value>
                <value>
                    <fullName>Review Code</fullName>
                </value>
                <value>
                    <fullName>Create testcase</fullName>
                </value>
                <value>
                    <fullName>Self-Review testcase</fullName>
                </value>
                <value>
                    <fullName>Correct testcase</fullName>
                </value>
                <value>
                    <fullName>Review testcase</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Re-test</fullName>
                </value>
                <value>
                    <fullName>Create Deploy Doc</fullName>
                </value>
                <value>
                    <fullName>Self-Review Deploy Doc</fullName>
                </value>
                <value>
                    <fullName>Correct Deploy Doc</fullName>
                </value>
                <value>
                    <fullName>Review Deploy Doc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Investigate</fullName>
                </value>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Deploy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_of_Project__c</fullName>
        <label>Task of Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Task of Project</relationshipLabel>
        <relationshipName>Task_of_Project</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>TSK{00000}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <recordTypes>
        <fullName>Code</fullName>
        <active>false</active>
        <label>Code</label>
    </recordTypes>
    <recordTypes>
        <fullName>Design</fullName>
        <active>true</active>
        <label>Design</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test2/Demo/force-app/main/default/classes/EmployeeTaskControllerTest.cls
@isTest
public with sharing class EmployeeTaskControllerTest {
    private static List<Employee__c> empList;
    private static List<Project__c> prjList;
    private static List<Task__c> taskList;

    public static void createTestData(){
        empList = new List<Employee__c>();
        prjList = new List<Project__c>();
        taskList = new List<Task__c>();


        Employee__c e1 = new Employee__c(Name__c='Hung_PM1', Birthday__c=Date.newInstance(1990,1,1), JoinDate__c=Date.newInstance(2013,1,1),  Mail__c='hung1@hung.hung', Role__c='Project manager');
        Employee__c e2 = new Employee__c(Name__c='Hiep_PM22', Birthday__c=Date.newInstance(1991,1,1), JoinDate__c=Date.newInstance(2014,1,1),  Mail__c='hiep2@hiep2.hiep2', Role__c='Project manager');
        Employee__c e3 = new Employee__c(Name__c='Hung_culi3', Birthday__c=Date.newInstance(1992,1,1), JoinDate__c=Date.newInstance(2015,1,1),  Mail__c='hung3@hung.hung', Role__c='Programmer');
        Employee__c e4 = new Employee__c(Name__c='Hung_culi4', Birthday__c=Date.newInstance(1993,1,1), JoinDate__c=Date.newInstance(2016,1,1),  Mail__c='hung4@hung.hung', Role__c='Programmer');
        Employee__c e5 = new Employee__c(Name__c='Hiep_culi5', Birthday__c=Date.newInstance(1994,1,1), JoinDate__c=Date.newInstance(2017,1,1),  Mail__c='hiep5@hiep5.hiep5', Role__c='Programmer');
        empList.add(e1);
        empList.add(e2);
        empList.add(e3);
        empList.add(e4);
        empList.add(e5);
        insert empList;

        // empList.clear();
        // empList = [SELECT Name, Name__c FROM Employee__c];

        Project__c prj1 = new Project__c(Name__c='BI Tool', PM_Name__c=empList.get(0).id);
        Project__c prj2 = new Project__c(Name__c='Cafe', PM_Name__c=empList.get(1).id);
        prjList.add(prj1);
        prjList.add(prj2);
        insert prjList;

        prjList.clear();
        prjList = [SELECT Name FROM Project__c];

        e3.Member_of_Project__c = prj1.id;
        e4.Member_of_Project__c = prj1.id;
        e5.Member_of_Project__c = prj2.id;

        upsert e3;
        upsert e4;
        upsert e5;
        // empList.clear();
        // empList.add(e1);
        // empList.add(e2);
        // empList.add(e3);
        // empList.add(e4);
        // empList.add(e5);

        Task__c t1 = new Task__c(Task_Type__c='Design', Process__c='Open', Task_of_Project__c=prj1.id);
        Task__c t2 = new Task__c(Task_Type__c='Code', Process__c='Open', Task_of_Project__c=prj1.id);
        Task__c t3 = new Task__c(Task_Type__c='Code', Process__c='Open', Task_of_Project__c=prj1.id);
        Task__c t4 = new Task__c(Task_Type__c='Design', Process__c='Open', Task_of_Project__c=prj2.id);
        Task__c t5 = new Task__c(Task_Type__c='Code', Process__c='Open', Task_of_Project__c=prj2.id);
        taskList.add(t1);
        taskList.add(t2);
        taskList.add(t3);
        taskList.add(t4);
        taskList.add(t5);
        insert taskList;
    }
    @isTest static void getEmployeeTaskListTest(){
        EmployeeTaskControllerTest.createTestData();
        Project__c biPrj = prjList.get(0);
        List<Task__c> actualTaskList = EmployeeTaskController.getEmployeeTaskList(biPrj.id);
        List<Task__c> expectedTaskList = new List<Task__c>();
        for(Task__c t : taskList){
            if(t.Task_of_Project__c == biPrj.id){
                expectedTaskList.add(t);
            }
        }
        System.assert(actualTaskList.size() > 0);
        System.assert(expectedTaskList.size() == 3);
        System.assert(expectedTaskList.size() == actualTaskList.size());
    }

    @isTest static void getTaskCountTest(){
        EmployeeTaskControllerTest.createTestData();
        Employee__c biPrjE1 = empList.get(2);
        Integer actualTaskListSize = EmployeeTaskController.getTaskCount(biPrjE1.id);
        List<Task__c> expectedTaskList = new List<Task__c>();
        for(Task__c t : taskList){
            if(t.Task_of_Project__c == biPrjE1.Member_of_Project__c){
                expectedTaskList.add(t);
            }
        }
        System.assert(actualTaskListSize == 3);
        System.assert(expectedTaskList.size() == 3);
    }
}