Test2/Demo/mdapipkg/unpackaged/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Member_of_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member of Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Member of Project</relationshipLabel>
        <relationshipName>Member_of_Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP{00000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test2/Demo/mdapipkg/unpackaged/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_of_Project__c</fullName>
        <label>Task of Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Task of Project</relationshipLabel>
        <relationshipName>Task_of_Project</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>TSK{00000}</displayFormat>
        <label>Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test2/Demo/mdapipkg/unpackaged/classes/EmployeeTaskController.cls
public with sharing class EmployeeTaskController {
    @AuraEnabled(cacheable=true)
    public static List<Task__c> getEmployeeTaskList(String projectID){
        return [SELECT Name, Name__c, Description__c FROM Task__c WHERE Task_of_Project__c = :projectID];
    }

    @AuraEnabled(cacheable=true)
    public static List<Task__c> getEmployeeTasks(String employeeID){
        // List<Task__c> empTaskList = new List<Task__c>();
        // List<Employee__c> empProjectIDList = [SELECT Member_of_Project__c from Employee__c where id = :employeeID];
        // for(Employee__c e : empProjectIDList){
        //     empTaskList.addAll(getEmployeeTaskList(e.Member_of_Project__c));
        // }
        // return empTaskList;
        return [SELECT Name, Name__c, Description__c FROM Task__c WHERE Task_of_Project__c IN (SELECT Member_of_Project__c from Employee__c where id = :employeeID)];
    }

    @AuraEnabled()
    public static integer getTaskCount(String employeeID){
        // List<AggregateResult> results= 
        //     [SELECT Count(Name) FROM Task__c WHERE Task_of_Project__c IN (SELECT Member_of_Project__c from Employee__c where id = :employeeID)];
        // return Integer.valueOf(results[0].get('expr0')+'');
        List<Task__c> result = getEmployeeTasks(employeeID);
        return result.size();
    }
}